apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: '5000'
  # the second mongodb is the name of the mongodb container, rename it to what you have
  DB_URL: 'mongodb://mongodb:27017/boilerplate'
  APP_ENV: 'production'
  ACCESS_SECRET: 'top secret'
  REFRESH_SECRET: 'top secret'
  ACCESS_TOKEN_EXPIRATION: '10m'
  REFRESH_TOKEN_EXPIRATION: '7d'
