# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests including MongoDB

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - name: Set up environment variables
        run: |
          echo DB_URL=${{ secrets.DB_URL }} >> .env
          echo ACCESS_SECRET=${{ secrets.ACCESS_SECRET }} >> .env
          echo ACCESS_TOKEN_EXPIRATION=${{ secrets.ACCESS_TOKEN_EXPIRATION }} >> .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo REFRESH_SECRET=${{ secrets.REFRESH_SECRET }} >> .env
          echo REFRESH_TOKEN_EXPIRATION=${{ secrets.REFRESH_TOKEN_EXPIRATION }} >> .env
      - run: npm run build --if-present
      - run: npm run test
      - run: npm run test:e2e
